
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author andre
 */
public class PantallaJuego extends javax.swing.JFrame implements ActionListener {
    
    private final int PANEL_WIDTH = 600;
    private final int PANEL_HEIGHT = 600;
    private Image backGroundImage;
    private Timer timer;
    private int xVelocity = 1;
    private int yVelocity = 1;
    private int x = 0;
    private int y = 0;
    
    private Cola colaUnidades = new Cola();
    private ListaDobleCirc caminoSuperior = new ListaDobleCirc();
    private ListaDobleCirc caminoInferior = new ListaDobleCirc();
    private Castillo castilloJugador = new Castillo();
    private Castillo CastilloCPU = new Castillo();
    private int numeroRonda = 1;
    private int segundos = 0; 
    private int minutos = 0;
    private int numTropasJugador = 0;
    private int numTropasCPU = 0;
    
    
    
    
    
    
    
    /**
     * Creates new form PantallaJuego
     */
    public PantallaJuego() {
        initComponents();
        
        Tropa arquero = new Tropa("arquero");
        Tropa mago = new Tropa("mago");
        Tropa caballero = new Tropa("caballero");
        
        colaUnidades.encola(new Nodo(arquero));
        colaUnidades.encola(new Nodo(mago));
        colaUnidades.encola(new Nodo(caballero));
        
        
        
        
        Camino caminoSup1 = new Camino();
        caminoSuperior.inserta(caminoSup1);
        Camino caminoSup2 = new Camino();
        caminoSuperior.inserta(caminoSup2);
        Camino caminoSup3 = new Camino();
        caminoSuperior.inserta(caminoSup3);
        Camino caminoSup4 = new Camino();
        caminoSuperior.inserta(caminoSup4);
        Camino caminoSup5 = new Camino();
        caminoSuperior.inserta(caminoSup5);
        Camino caminoInf1 = new Camino();
        caminoSuperior.inserta(caminoInf1);
        Camino caminoInf2 = new Camino();
        caminoSuperior.inserta(caminoInf2);
        Camino caminoInf3 = new Camino();
        caminoSuperior.inserta(caminoInf3);
        Camino caminoInf4 = new Camino();
        caminoSuperior.inserta(caminoInf4);
        Camino caminoInf5 = new Camino();
        caminoSuperior.inserta(caminoInf5);
        
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        board = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        gamePanel = new javax.swing.JPanel();
        boardLabel = new javax.swing.JLabel();
        seleccionTropasBT = new javax.swing.JButton();
        caminoSuperiorBT = new javax.swing.JButton();
        caminoInferiorBT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        vidaJugadorTxt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        temporizadorPanel = new javax.swing.JPanel();
        vidaJugadorPanel = new javax.swing.JPanel();
        vidaCPUPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        board.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Board(1).png"))); // NOI18N

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gamePanel.setBackground(new java.awt.Color(102, 102, 102));

        boardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Board(1).png"))); // NOI18N

        seleccionTropasBT.setBackground(new java.awt.Color(255, 153, 51));
        seleccionTropasBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        seleccionTropasBT.setText("Seleccionador tropas");

        caminoSuperiorBT.setBackground(new java.awt.Color(255, 204, 102));
        caminoSuperiorBT.setText("Camino Superior");

        caminoInferiorBT.setBackground(new java.awt.Color(255, 204, 102));
        caminoInferiorBT.setText("Camino Inferior");
        caminoInferiorBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caminoInferiorBTActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vida CPU:");

        vidaJugadorTxt.setBackground(new java.awt.Color(255, 51, 51));
        vidaJugadorTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vidaJugadorTxt.setForeground(new java.awt.Color(255, 255, 255));
        vidaJugadorTxt.setText("Vida Jugador:  ");

        jLabel2.setText("Temporizador");

        javax.swing.GroupLayout temporizadorPanelLayout = new javax.swing.GroupLayout(temporizadorPanel);
        temporizadorPanel.setLayout(temporizadorPanelLayout);
        temporizadorPanelLayout.setHorizontalGroup(
            temporizadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
        );
        temporizadorPanelLayout.setVerticalGroup(
            temporizadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout vidaJugadorPanelLayout = new javax.swing.GroupLayout(vidaJugadorPanel);
        vidaJugadorPanel.setLayout(vidaJugadorPanelLayout);
        vidaJugadorPanelLayout.setHorizontalGroup(
            vidaJugadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );
        vidaJugadorPanelLayout.setVerticalGroup(
            vidaJugadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout vidaCPUPanelLayout = new javax.swing.GroupLayout(vidaCPUPanel);
        vidaCPUPanel.setLayout(vidaCPUPanelLayout);
        vidaCPUPanelLayout.setHorizontalGroup(
            vidaCPUPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        vidaCPUPanelLayout.setVerticalGroup(
            vidaCPUPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanelLayout.createSequentialGroup()
                .addComponent(boardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gamePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(caminoSuperiorBT, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                .addComponent(caminoInferiorBT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(seleccionTropasBT)
                            .addComponent(temporizadorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vidaJugadorTxt)))
                    .addGroup(gamePanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2))
                    .addGroup(gamePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(vidaJugadorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gamePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(vidaCPUPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gamePanelLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(boardLabel))
            .addGroup(gamePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(seleccionTropasBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(caminoSuperiorBT)
                .addGap(18, 18, 18)
                .addComponent(vidaJugadorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vidaJugadorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vidaCPUPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(caminoInferiorBT)
                .addGap(82, 82, 82)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(temporizadorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gamePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gamePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caminoInferiorBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caminoInferiorBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caminoInferiorBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel board;
    private javax.swing.JLabel boardLabel;
    private javax.swing.JButton caminoInferiorBT;
    private javax.swing.JButton caminoSuperiorBT;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JButton seleccionTropasBT;
    private javax.swing.JPanel temporizadorPanel;
    private javax.swing.JPanel vidaCPUPanel;
    private javax.swing.JPanel vidaJugadorPanel;
    private javax.swing.JLabel vidaJugadorTxt;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) { 
    }
}
